name: CI
on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:
jobs:
  ci:
    runs-on: ${{ matrix. os }}
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows
            os: windows-2022
          - name: Linux
            os: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        uses: ./
        with:
          connection-string-env-var: SQL_CONN_STR
          catalog: my-test-catalog
      - name: Check result
        shell: pwsh
        run: |
          $connstr = $Env:SQL_CONN_STR
          Write-Host "Connection String: $connstr"

          $result = sqlcmd -Q "SELECT DB_NAME() as CatalogName" -d "my-test-catalog"
          echo $result
